[package]
name = "rdf-canon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base16ct = "0.1.1"
itertools = "0.10.5"
nanoid = "0.4.0"
sha2 = "0.10.6"
thiserror = "1.0.38"
